ml_platform_homepage:
    path:     /{page}
    defaults:
        _controller: MLPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*

ml_platform_view:
    path:     /advert/{id}
    defaults:
        _controller: MLPlatformBundle:Advert:view
    requirements:
        id: \d+

ml_platform_add:
    path:     /add
    defaults:
        _controller: MLPlatformBundle:Advert:add

ml_platform_edit:
    path:     /edit/{id}
    defaults:
        _controller: MLPlatformBundle:Advert:edit
    requirements:
        id: \d+

ml_platform_delete:
    path:     /delete/{id}
    defaults:
        _controller: MLPlatformBundle:Advert:delete
    requirements:
        id: \d+
